version: '3.4'
services:
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    volumes:
    - /data
    container_name: redis

  mongodb:
    image: mongo:3.6
    ports:
    - "27017:27017"
    volumes:
    - /data/db
    container_name: mongodb
 